name: Build & Publish

on:
  workflow_dispatch:

jobs:
  Build & Publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Install NuGet
      uses: NuGet/setup-nuget@v1
    - name: Publish FontStashSharp to NuGet
      shell: pwsh
      run: nuget.exe push .\src\FontStashSharp\bin\Release\FontStashSharp.*.nupkg ${NUGET_APIKEY} -Source https://api.nuget.org/v3/index.json
    - name: Publish FontStashSharp.StbTrueTypeSharp to NuGet
      shell: pwsh
      run: nuget.exe push .\src\FontStashSharp.StbTrueTypeSharp\bin\Release\FontStashSharp.StbTrueTypeSharp.*.nupkg ${NUGET_APIKEY} -Source https://api.nuget.org/v3/index.json
